import {
  Doctor,
  Clinic,
  Patient,
  Appointment,
  QueueEntry,
  Payment,
  VerificationDoc,
  Review,
  Notification,
  SupportTicket,
  ChartDataPoint,
} from "@/types";

export const dummyDoctors: Doctor[] = [
  {
    id: "d1",
    name: "Dr. James Sterling",
    email: "james.s@pulsemd.com",
    initials: "JS",
    specialization: "Cardiology",
    clinic: "City View Medical",
    clinicId: "c1",
    status: "active",
    verificationStatus: "approved",
    rating: 4.9,
    totalAppointments: 1240,
    earnings: 124500,
    phone: "+1 555-0101",
    experience: 12,
    joinedAt: "2022-01-15",
    documents: [],
  },
  {
    id: "d2",
    name: "Dr. Sarah Vance",
    email: "s.vance@pulsemd.com",
    initials: "SV",
    specialization: "Neurology",
    clinic: "Central Neuro Clinic",
    clinicId: "c2",
    status: "active",
    verificationStatus: "pending",
    rating: 4.7,
    totalAppointments: 856,
    earnings: 85600,
    phone: "+1 555-0102",
    experience: 8,
    joinedAt: "2022-06-20",
    documents: [],
  },
  {
    id: "d3",
    name: "Dr. Alan Gregson",
    email: "gregson.a@clinic.org",
    initials: "AG",
    specialization: "Pediatrics",
    clinic: "St. Jude Pediatric",
    clinicId: "c3",
    status: "inactive",
    verificationStatus: "rejected",
    rating: 4.2,
    totalAppointments: 412,
    earnings: 41200,
    phone: "+1 555-0103",
    experience: 5,
    joinedAt: "2023-02-10",
    documents: [],
  },
  {
    id: "d4",
    name: "Dr. Maria Lopez",
    email: "maria.l@pulsemd.com",
    initials: "ML",
    specialization: "Oncology",
    clinic: "Hope Wellness Lab",
    clinicId: "c4",
    status: "active",
    verificationStatus: "approved",
    rating: 5.0,
    totalAppointments: 2084,
    earnings: 208400,
    phone: "+1 555-0104",
    experience: 15,
    joinedAt: "2021-11-05",
    documents: [],
  },
  {
    id: "d5",
    name: "Dr. Elias Vance",
    email: "elias.v@pulsemd.com",
    initials: "EV",
    specialization: "Neurology",
    clinic: "St. Mary's Hospital",
    clinicId: "c5",
    status: "active",
    verificationStatus: "approved",
    rating: 4.8,
    totalAppointments: 1580,
    earnings: 158000,
    phone: "+1 555-0105",
    experience: 10,
    joinedAt: "2021-08-12",
    documents: [],
  },
  {
    id: "d6",
    name: "Dr. Sarah Jenkins",
    email: "sarah.j@pulsemd.com",
    initials: "SJ",
    specialization: "Orthopedics",
    clinic: "City General",
    clinicId: "c1",
    status: "active",
    verificationStatus: "approved",
    rating: 4.9,
    totalAppointments: 142,
    earnings: 14200,
    phone: "+1 555-0106",
    experience: 7,
    joinedAt: "2023-09-01",
    documents: [],
  },
  {
    id: "d7",
    name: "Dr. Michael Chen",
    email: "michael.c@pulsemd.com",
    initials: "MC",
    specialization: "Pediatrics",
    clinic: "Westside Clinic",
    clinicId: "c6",
    status: "active",
    verificationStatus: "approved",
    rating: 4.8,
    totalAppointments: 128,
    earnings: 12800,
    phone: "+1 555-0107",
    experience: 6,
    joinedAt: "2023-10-15",
    documents: [],
  },
  {
    id: "d8",
    name: "Dr. Elena Rodriguez",
    email: "elena.r@pulsemd.com",
    initials: "ER",
    specialization: "Dermatology",
    clinic: "Skin & Care Center",
    clinicId: "c7",
    status: "active",
    verificationStatus: "approved",
    rating: 4.7,
    totalAppointments: 115,
    earnings: 11500,
    phone: "+1 555-0108",
    experience: 9,
    joinedAt: "2023-07-22",
    documents: [],
  },
];

export const dummyClinics: Clinic[] = [
  {
    id: "c1",
    name: "City View Medical",
    location: "123 Main St",
    city: "New York",
    doctorsAssigned: 12,
    status: "active",
    dailyAppointments: 145,
    rating: 4.8,
    phone: "+1 555-1001",
    email: "admin@cityview.com",
    timings: "Mon–Sat: 8AM–8PM",
    tokenCapacity: 50,
    services: ["Cardiology", "Orthopedics", "General Medicine"],
    consultationFee: 150,
  },
  {
    id: "c2",
    name: "Central Neuro Clinic",
    location: "456 Park Ave",
    city: "Chicago",
    doctorsAssigned: 8,
    status: "active",
    dailyAppointments: 89,
    rating: 4.7,
    phone: "+1 555-1002",
    email: "admin@centralneuro.com",
    timings: "Mon–Fri: 9AM–6PM",
    tokenCapacity: 30,
    services: ["Neurology", "Psychiatry"],
    consultationFee: 200,
  },
  {
    id: "c3",
    name: "St. Jude Pediatric",
    location: "789 Oak Blvd",
    city: "Los Angeles",
    doctorsAssigned: 6,
    status: "inactive",
    dailyAppointments: 45,
    rating: 4.5,
    phone: "+1 555-1003",
    email: "admin@stjude.com",
    timings: "Mon–Sat: 10AM–5PM",
    tokenCapacity: 20,
    services: ["Pediatrics", "Vaccination"],
    consultationFee: 120,
  },
  {
    id: "c4",
    name: "Hope Wellness Lab",
    location: "321 Elm St",
    city: "Houston",
    doctorsAssigned: 15,
    status: "active",
    dailyAppointments: 210,
    rating: 4.9,
    phone: "+1 555-1004",
    email: "admin@hopewellness.com",
    timings: "Daily: 7AM–9PM",
    tokenCapacity: 70,
    services: ["Oncology", "Radiology", "Surgery"],
    consultationFee: 300,
  },
  {
    id: "c5",
    name: "St. Mary's Hospital",
    location: "654 Birch Rd",
    city: "Phoenix",
    doctorsAssigned: 25,
    status: "active",
    dailyAppointments: 320,
    rating: 4.6,
    phone: "+1 555-1005",
    email: "admin@stmarys.com",
    timings: "24/7",
    tokenCapacity: 100,
    services: ["Emergency", "Surgery", "ICU", "General Medicine"],
    consultationFee: 180,
  },
];

export const dummyPatients: Patient[] = [
  {
    id: "p1",
    name: "Elena Rodriguez",
    phone: "+1 555-2001",
    email: "elena.r@email.com",
    initials: "ER",
    totalAppointments: 12,
    lastVisit: "2024-10-20",
    status: "active",
    age: 34,
    bloodGroup: "O+",
    address: "123 West St, NY",
    joinedAt: "2022-03-10",
  },
  {
    id: "p2",
    name: "Robert Chen",
    phone: "+1 555-2002",
    email: "robert.c@email.com",
    initials: "RC",
    totalAppointments: 7,
    lastVisit: "2024-10-18",
    status: "active",
    age: 45,
    bloodGroup: "A+",
    address: "456 East Ave, LA",
    joinedAt: "2022-07-22",
  },
  {
    id: "p3",
    name: "Marcus Kim",
    phone: "+1 555-2003",
    email: "marcus.k@email.com",
    initials: "MK",
    totalAppointments: 3,
    lastVisit: "2024-09-05",
    status: "blocked",
    age: 28,
    bloodGroup: "B-",
    address: "789 North Blvd, Chicago",
    joinedAt: "2023-01-15",
  },
  {
    id: "p4",
    name: "Tasha Wright",
    phone: "+1 555-2004",
    email: "tasha.w@email.com",
    initials: "TW",
    totalAppointments: 18,
    lastVisit: "2024-10-22",
    status: "active",
    age: 52,
    bloodGroup: "AB+",
    address: "321 South St, Houston",
    joinedAt: "2021-11-30",
  },
  {
    id: "p5",
    name: "James Patterson",
    phone: "+1 555-2005",
    email: "james.p@email.com",
    initials: "JP",
    totalAppointments: 5,
    lastVisit: "2024-10-15",
    status: "active",
    age: 38,
    bloodGroup: "O-",
    address: "654 Pine Ave, Phoenix",
    joinedAt: "2023-04-08",
  },
  {
    id: "p6",
    name: "Sofia Martinez",
    phone: "+1 555-2006",
    email: "sofia.m@email.com",
    initials: "SM",
    totalAppointments: 9,
    lastVisit: "2024-10-19",
    status: "active",
    age: 29,
    bloodGroup: "A-",
    address: "987 Oak St, Miami",
    joinedAt: "2022-09-14",
  },
];

export const dummyAppointments: Appointment[] = [
  {
    id: "apt001",
    patientName: "Elena Rodriguez",
    patientId: "p1",
    doctorName: "Dr. James Sterling",
    doctorId: "d1",
    clinic: "City View Medical",
    clinicId: "c1",
    date: "2024-10-24",
    time: "09:30 AM",
    tokenNumber: 12,
    status: "completed",
    paymentStatus: "paid",
    amount: 150,
  },
  {
    id: "apt002",
    patientName: "Robert Chen",
    patientId: "p2",
    doctorName: "Dr. Sarah Vance",
    doctorId: "d2",
    clinic: "Central Neuro Clinic",
    clinicId: "c2",
    date: "2024-10-24",
    time: "11:00 AM",
    tokenNumber: 8,
    status: "in-progress",
    paymentStatus: "paid",
    amount: 200,
  },
  {
    id: "apt003",
    patientName: "Marcus Kim",
    patientId: "p3",
    doctorName: "Dr. Alan Gregson",
    doctorId: "d3",
    clinic: "St. Jude Pediatric",
    clinicId: "c3",
    date: "2024-10-23",
    time: "02:00 PM",
    tokenNumber: 5,
    status: "cancelled",
    paymentStatus: "refunded",
    amount: 120,
  },
  {
    id: "apt004",
    patientName: "Tasha Wright",
    patientId: "p4",
    doctorName: "Dr. Maria Lopez",
    doctorId: "d4",
    clinic: "Hope Wellness Lab",
    clinicId: "c4",
    date: "2024-10-25",
    time: "10:15 AM",
    tokenNumber: 3,
    status: "scheduled",
    paymentStatus: "paid",
    amount: 300,
  },
  {
    id: "apt005",
    patientName: "James Patterson",
    patientId: "p5",
    doctorName: "Dr. Elias Vance",
    doctorId: "d5",
    clinic: "St. Mary's Hospital",
    clinicId: "c5",
    date: "2024-10-24",
    time: "03:30 PM",
    tokenNumber: 21,
    status: "scheduled",
    paymentStatus: "pending",
    amount: 180,
  },
  {
    id: "apt006",
    patientName: "Sofia Martinez",
    patientId: "p6",
    doctorName: "Dr. Sarah Jenkins",
    doctorId: "d6",
    clinic: "City View Medical",
    clinicId: "c1",
    date: "2024-10-22",
    time: "01:00 PM",
    tokenNumber: 15,
    status: "completed",
    paymentStatus: "paid",
    amount: 150,
  },
];

export const dummyQueue: QueueEntry[] = [
  {
    id: "q1",
    doctorName: "Dr. James Sterling",
    doctorId: "d1",
    clinic: "City View Medical",
    currentToken: 12,
    waitingPatients: 8,
    avgWaitTime: 15,
    status: "active",
    totalTokens: 50,
  },
  {
    id: "q2",
    doctorName: "Dr. Sarah Vance",
    doctorId: "d2",
    clinic: "Central Neuro Clinic",
    currentToken: 5,
    waitingPatients: 12,
    avgWaitTime: 22,
    status: "active",
    totalTokens: 30,
  },
  {
    id: "q3",
    doctorName: "Dr. Maria Lopez",
    doctorId: "d4",
    clinic: "Hope Wellness Lab",
    currentToken: 18,
    waitingPatients: 3,
    avgWaitTime: 8,
    status: "paused",
    totalTokens: 70,
  },
  {
    id: "q4",
    doctorName: "Dr. Elias Vance",
    doctorId: "d5",
    clinic: "St. Mary's Hospital",
    currentToken: 7,
    waitingPatients: 15,
    avgWaitTime: 30,
    status: "active",
    totalTokens: 100,
  },
];

export const dummyPayments: Payment[] = [
  {
    id: "pay1",
    doctorName: "Dr. Elias Vance",
    doctorId: "d5",
    specialization: "Neurology",
    clinic: "St. Mary's",
    paymentId: "#PY-82910-VX",
    amount: 12450,
    status: "completed",
    payoutDate: "Oct 24, 2023 • 14:20",
    initials: "EV",
  },
  {
    id: "pay2",
    doctorName: "Dr. Sarah Jenkins",
    doctorId: "d6",
    specialization: "Orthopedics",
    clinic: "City General",
    paymentId: "#PY-82911-SJ",
    amount: 8920,
    status: "processing",
    payoutDate: "Oct 24, 2023 • 09:15",
    initials: "SJ",
  },
  {
    id: "pay3",
    doctorName: "Dr. Michael Chen",
    doctorId: "d7",
    specialization: "Pediatrics",
    clinic: "Westside Clinic",
    paymentId: "#PY-82912-MC",
    amount: 15100,
    status: "completed",
    payoutDate: "Oct 23, 2023 • 17:45",
    initials: "MC",
  },
  {
    id: "pay4",
    doctorName: "Dr. Amara Okoro",
    doctorId: "d9",
    specialization: "Cardiology",
    clinic: "Heart Institute",
    paymentId: "#PY-82913-AO",
    amount: 22340,
    status: "failed",
    payoutDate: "Oct 23, 2023 • 11:30",
    initials: "AO",
  },
  {
    id: "pay5",
    doctorName: "Dr. James Sterling",
    doctorId: "d1",
    specialization: "Cardiology",
    clinic: "City View Medical",
    paymentId: "#PY-82914-JS",
    amount: 18750,
    status: "completed",
    payoutDate: "Oct 22, 2023 • 16:00",
    initials: "JS",
  },
];

export const dummyVerifications: VerificationDoc[] = [
  {
    id: "v1",
    doctorName: "Dr. Elias Jenkins",
    doctorId: "dv1",
    specialization: "Cardiology",
    initials: "EJ",
    documentType: "Medical License",
    uploadDate: "Oct 24, 2023",
    status: "pending",
    fileType: "pdf",
  },
  {
    id: "v2",
    doctorName: "Dr. Sarah Al-Farsi",
    doctorId: "dv2",
    specialization: "Neurology",
    initials: "SA",
    documentType: "Board Degree",
    uploadDate: "Oct 23, 2023",
    status: "verified",
    fileType: "image",
  },
  {
    id: "v3",
    doctorName: "Dr. Marcus Krell",
    doctorId: "dv3",
    specialization: "General Surgery",
    initials: "MK",
    documentType: "Gov Identity ID",
    uploadDate: "Oct 22, 2023",
    status: "rejected",
    fileType: "pdf",
  },
  {
    id: "v4",
    doctorName: "Dr. Lena Chen",
    doctorId: "dv4",
    specialization: "Pediatrics",
    initials: "LC",
    documentType: "Medical License",
    uploadDate: "Oct 24, 2023",
    status: "pending",
    fileType: "image",
  },
];

export const dummyReviews: Review[] = [
  {
    id: "r1",
    patientName: "Elena Rodriguez",
    patientId: "p1",
    doctorName: "Dr. Julian Vance",
    doctorId: "d10",
    rating: 5,
    reviewText: "Wait times were minimal and the doctor was very thorough. Highly recommend!",
    date: "12 Jun 2024",
    status: "published",
  },
  {
    id: "r2",
    patientName: "Robert Chen",
    patientId: "p2",
    doctorName: "Dr. Sarah Liana",
    doctorId: "d11",
    rating: 5,
    reviewText: "Extremely professional and knowledgeable. Got an accurate diagnosis immediately.",
    date: "11 Jun 2024",
    status: "flagged",
  },
  {
    id: "r3",
    patientName: "Marcus Kim",
    patientId: "p3",
    doctorName: "Dr. Emily Stone",
    doctorId: "d12",
    rating: 2,
    reviewText: "Billing dispute. This is unacceptable behavior for a medical professional.",
    date: "09 Jun 2024",
    status: "resolved",
  },
  {
    id: "r4",
    patientName: "Tasha Wright",
    patientId: "p4",
    doctorName: "Dr. Michael Thorne",
    doctorId: "d13",
    rating: 5,
    reviewText: "Highly recommend! Dr. Thorne took extra time to explain my treatment plan.",
    date: "08 Jun 2024",
    status: "published",
  },
];

export const dummyNotifications: Notification[] = [
  {
    id: "n1",
    title: "Emergency System Patch",
    audience: "clinics",
    channel: ["push", "email"],
    status: "delivered",
    sentAt: "2h ago",
    reachCount: 248,
  },
  {
    id: "n2",
    title: "Holiday Hours Update",
    audience: "patients",
    channel: ["sms"],
    status: "delivered",
    sentAt: "5h ago",
    reachCount: 8450,
  },
  {
    id: "n3",
    title: "Onboarding: New Doctors",
    audience: "doctors",
    channel: ["email"],
    status: "queued",
    sentAt: "1d ago",
    reachCount: 124,
  },
  {
    id: "n4",
    title: "Policy Revision Update",
    audience: "doctors",
    channel: ["push"],
    status: "delivered",
    sentAt: "10m ago",
    reachCount: 1240,
  },
  {
    id: "n5",
    title: "COVID-19 Advisory",
    audience: "clinics",
    channel: ["push"],
    status: "delivered",
    sentAt: "Yesterday",
    reachCount: 35,
  },
];

export const dummySupportTickets: SupportTicket[] = [
  {
    id: "TKT-001",
    userId: "p1",
    userName: "Elena Rodriguez",
    userType: "patient",
    category: "Billing",
    status: "open",
    priority: "high",
    assignedTo: "Support Team A",
    createdAt: "2024-10-24",
    subject: "Incorrect charge on last appointment",
  },
  {
    id: "TKT-002",
    userId: "d2",
    userName: "Dr. Sarah Vance",
    userType: "doctor",
    category: "Technical",
    status: "pending",
    priority: "medium",
    assignedTo: "Dev Team",
    createdAt: "2024-10-23",
    subject: "Cannot access patient records",
  },
  {
    id: "TKT-003",
    userId: "p4",
    userName: "Tasha Wright",
    userType: "patient",
    category: "Appointment",
    status: "resolved",
    priority: "low",
    assignedTo: "Support Team B",
    createdAt: "2024-10-22",
    subject: "Reschedule request not processed",
  },
  {
    id: "TKT-004",
    userId: "d1",
    userName: "Dr. James Sterling",
    userType: "doctor",
    category: "Payout",
    status: "escalated",
    priority: "critical",
    assignedTo: "Finance Team",
    createdAt: "2024-10-21",
    subject: "Payment not received for October",
  },
  {
    id: "TKT-005",
    userId: "p6",
    userName: "Sofia Martinez",
    userType: "patient",
    category: "Account",
    status: "open",
    priority: "medium",
    assignedTo: "Unassigned",
    createdAt: "2024-10-24",
    subject: "Unable to login to patient portal",
  },
];

// Chart data
export const appointmentTrendData: ChartDataPoint[] = [
  { name: "Mon", value: 42, secondary: 35 },
  { name: "Tue", value: 68, secondary: 58 },
  { name: "Wed", value: 55, secondary: 48 },
  { name: "Thu", value: 85, secondary: 72 },
  { name: "Fri", value: 112, secondary: 95 },
  { name: "Sat", value: 143, secondary: 128 },
  { name: "Sun", value: 98, secondary: 85 },
];

export const revenueData: ChartDataPoint[] = [
  { name: "Jan", value: 185000 },
  { name: "Feb", value: 210000 },
  { name: "Mar", value: 195000 },
  { name: "Apr", value: 284500 },
  { name: "May", value: 245000 },
  { name: "Jun", value: 265000 },
];

export const patientGrowthData: ChartDataPoint[] = [
  { name: "Apr", value: 5200 },
  { name: "May", value: 6100 },
  { name: "Jun", value: 6800 },
  { name: "Jul", value: 7400 },
  { name: "Aug", value: 7900 },
  { name: "Sep", value: 8200 },
  { name: "Oct", value: 8450 },
];

export const sentimentData: ChartDataPoint[] = [
  { name: "Mar", value: 82 },
  { name: "Apr", value: 75 },
  { name: "May", value: 88 },
  { name: "Jun", value: 65 },
  { name: "Jul", value: 90 },
  { name: "Aug", value: 87 },
];

export const recentActivity = [
  {
    id: "a1",
    type: "doctor_registration",
    title: "New Doctor Registration",
    description: "Dr. Aris Thorne completed verification for Cardiology Unit in Downtown Clinic.",
    time: "2 mins ago",
    color: "red",
  },
  {
    id: "a2",
    type: "system",
    title: "System Audit Complete",
    description: "Global security sweep performed. All clinical nodes reporting healthy.",
    time: "45 mins ago",
    color: "green",
  },
  {
    id: "a3",
    type: "patient_milestone",
    title: "Patient Milestone",
    description: "Total patient registry reached the 8k threshold for Q3 targets.",
    time: "1 hour ago",
    color: "red",
  },
  {
    id: "a4",
    type: "revenue",
    title: "Revenue Alert",
    description: "Payment gateway sync successful. $12.4k processed in last session.",
    time: "3 hours ago",
    color: "red",
  },
];
